-- 1. Crear la tabla para almacenar los datos del liderazgo
CREATE TABLE public.liderazgo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  nombre text NOT NULL,
  rol text,
  foto_url text,
  bio text,
  zona text -- Campo adicional para pastores de zona
);

-- 2. Habilitar Row Level Security (RLS) en la tabla
ALTER TABLE public.liderazgo ENABLE ROW LEVEL SECURITY;

-- 3. Crear políticas de acceso
-- Política para permitir el acceso público de lectura (SELECT)
CREATE POLICY "Public read access for leadership" ON public.liderazgo
  FOR SELECT USING (true);

-- Política para permitir a los usuarios autenticados (administradores) gestionar los datos (INSERT, UPDATE, DELETE)
CREATE POLICY "Allow authenticated users to manage leadership" ON public.liderazgo
  FOR ALL USING (auth.role() = 'authenticated');
